package com.chatbot.ai_chatbot_backend.service;

import com.chatbot.ai_chatbot_backend.model.ChatResponse;
import org.springframework.stereotype.Service;

import java.time.Instant;

@Service
public class ChatService {

    private final NlpService nlpService;

    public ChatService(NlpService nlpService) {
        this.nlpService = nlpService;
    }

    public ChatResponse handleMessage(String message) {
        var analysis = nlpService.analyze(message);

        String reply;
        switch (analysis.getIntent()) {
            case "greeting" -> reply = "Hello! How can I help you today?";
            case "goodbye" -> reply = "Goodbye! Feel free to message me anytime.";
            case "ask_time" -> reply = "Current server time: " + Instant.now();
            case "ask_weather" -> {
                String loc = analysis.getEntities().getOrDefault("location", "your area");
                reply = "I can’t fetch live weather yet, but you asked about " + loc + ".";
            }
            case "smalltalk_thanks" -> reply = "You're welcome! Anything else?";
            case "about_you" -> reply = "I am AI Chat Bot generated by Buddhbhushan and I am continously on development.., Now I am not ready ans limited que. but in future i will definatly rise about the sky..!";
            default -> reply = "I heard: '" + message + "'. Try asking me about time, weather, or just say hi!";
        }

        ChatResponse response = new ChatResponse();
        response.setReply(reply);
        response.setIntent(analysis.getIntent());
        response.setEntities(analysis.getEntities());
        response.setTimestamp(Instant.now().toString());

        return response;
    }
}

